apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webpage-upload

resources:
  - namespace.yaml
  - postgres.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingress.yaml
  - certificate.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: webpage-upload
  app.kubernetes.io/managed-by: kustomize
