apiVersion: v1
kind: Service
metadata:
  name: webpage-upload
  namespace: webpage-upload
  labels:
    app: webpage-upload
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: webpage-upload
